### ISSUE TITLE
Can't test my integration due to "corrupted" built file

### ISSUE THREAD

**Issue by Kulgar** [DevartSoftware/tmetric-plugins#25]
Hello, 

I am trying to add an integration for Open Project - a project management app like Jira or Redmine: https://www.openproject.org/

I've followed the wiki and looked at Jira's integration to have some kind of a complete example. 

But, when I am trying to test the build using the .xpi file for firefox or the folder for chrome, I have some errors. Firefox says that the extension seems to be corrupted. 

And chrome says: "impossible to load the background script 'lib/jquery.signalr.min.js'". 

Am I missing something? 
Here is my fork: https://github.com/ct2c/tmetric-plugins
And my only commit so far: https://github.com/ct2c/tmetric-plugins/commit/be46d8a7bdaea5f6c3c26e936d93a675956d5a22

Thanks in advance for your help.

**Comment by ArtemAvramenko** [comment]
What OS do you use? Did you call ```npm install``` before build? 

Also you can do pull request so we will include your modifications into next release.

**Comment by Kulgar** [comment]
Yes I did `npm install` :)
I'm using Ubuntu 16.04 LTS
And I tested builds in Ubuntu Firefox, Chrome Windows 10 and Firefox Windows 10.

I didn't want to do pull request as I did not managed to test my modifications. But sure, I can do the PR.
