### ISSUE TITLE
Notion integration

### ISSUE THREAD

**Issue by leon0399** [DevartSoftware/tmetric-plugins#38]
If there is no plans of TMetric team to work on Notion integration, I'm looking into integrating it myself:

# Interface
My plan is to add button, positioned at red rectangle
![image](https://user-images.githubusercontent.com/1759654/84806800-ed91af80-b00e-11ea-99be-62ef87136e36.png)

# Main issue

Notion uses quite long IDs for its pages, e.g. `59021d0b712d4338b189619876a30dcd` (32 chars)   
Isn't it going to be an problem for TMetric?

**Comment by ArtemAvramenko** [comment]
Issue ID length is limited as 128 characters
