### ISSUE TITLE
Tmetric button not load in ajax mode

### ISSUE THREAD

**Issue by m0st4f4** [DevartSoftware/tmetric-plugins#42]
Hi , we want add Tmetric button to our private app ,we use jQuery ajax to load data in tables and pages and add Tmetric Button to code but Tmetric extension can't locate placeholder because tmetric placeholder added after page loading 
how can I fix this problem?

`<div class="tmetric-button play-list"
     data-issue-name="Very important task"
     data-issue-id="task-123"
     data-issue-url="/tasks/123/"
     data-service-url="https://private.mycompany.com"
     data-project-name="My Awesome Project"
     data-tag-names="urgent,service"></div>`

[https://github.com/DevartSoftware/tmetric-plugins/wiki/How-to:-Integrate-TMetric-with-Private-Web-App](url)

**Comment by ArtemAvramenko** [comment]
Hi,

You should specify your domain on the extension settings page:
![image](https://user-images.githubusercontent.com/11413326/119464241-3556a600-bd4b-11eb-9ae4-85fedb8f6093.png)

**Comment by m0st4f4** [comment]
> Hi,
> 
> You should specify your domain on the extension settings page:
> ![image](https://user-images.githubusercontent.com/11413326/119464241-3556a600-bd4b-11eb-9ae4-85fedb8f6093.png)

I added domain to extension setting before, sometime tmetric button not display for example in ajax data load , or iframe

**Comment by ArtemAvramenko** [comment]
TMetric extension works on dozens of systems that use ajax, so it shouldn't be a problem.

But as for iframe, frames are not currently supported for generic integrations. If you have a real case, we can add a frame integration to the next version.

Also you can give us temporary access to your site (write to support@tmetric.com), so we can help you fix the problem.
