### ISSUE TITLE
Tmetric Button not more showing in Firefox

### ISSUE THREAD

**Issue by virtualweb-at** [DevartSoftware/tmetric-plugins#48]
On all of our GitLab Issues the Tmetric Button has gone. This happens around 1 week ago.

It is gone on current Firefox Versions, on Windows 11 and Ubuntu 21.

I can't see any Network Requests to tmetric.com.

**Comment by phil-davis** [comment]
The TMetric start-stop button is also gone on GitHub. It disappeared at the start of this week (maybe some time over the weekend or last Friday) on Firefox. It has disappeared on Chrome this morning. I see that version 4.4.1 of the add-on was released to Firefox about a week ago, and to Chrome yesterday. That matches with the days that the button went missing for me.

All our staff are reporting this problem this morning.

I have tried the standard "call centre" fixes - restarting the browser, removing and adding the extension again... but can't the TMetric button to appear.

**Comment by pieterbeens** [comment]
Same issue here. Using TMetric mostly with Zendesk, but the start-button just seems completely broken. I just submitted a support ticket via https://tmetric.com/support, hope this helps.

**Comment by ArtemAvramenko** [comment]
The problem was confirmed. The hotfix will be published during this day.

**Comment by phil-davis** [comment]
I have updated in Firefox and it is working now. Version is 4.4.2
I tried updating in Google chrome and can't get the TMetric button to appear on my GitHub pages. Version is still 4.41
@ArtemAvramenko is a Google Chrome fix coming?

**Comment by ArtemAvramenko** [comment]
On average, Google reviews an extension within one day before publishing it to the Chrome Web Store. The update is already available.

**Comment by phil-davis** [comment]
I refreshed a GitHub issue on chrome just now, and the TMetric button appears - fixed, thanks.

That's a bit sad that if someone publishes an accidentally broken extension version, that they can't publish the fix and force it to apply immediately, or at least get high-priority review in 5 minutes.
